### PR TITLE
fix(monaco): preserve Markdown font styles (bold, italic, strikethrou…

### LINKED ISSUE #1022: `shikiToMonaco` doesn't preserve bold, italics, and more in Markdown
### Validations

- [x] Follow our [Code of Conduct](https://github.com/shikijs/shiki/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [Contributing Guide](https://github.com/shikijs/shiki/blob/main/CONTRIBUTING.md).
- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

### Describe the bug

The `shikiToMonaco` utility to use a Shiki highlighter in Monaco Editor doesn't preserve the bold or italic styles from the theme when used with Markdown code. It may affect more than Markdown, but I've only tested Markdown.

### Reproduction

https://codesandbox.io/p/sandbox/confident-mahavira-lphwdf

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

### PR DESCRIPTION
**Pull request by prempyla**
…gh) (#1022)

### Description
This PR fixes an issue where shikiToMonaco failed to preserve Markdown text styles (bold, italic, strikethrough) when integrating Shiki themes into the Monaco Editor.
Previously, Monaco tokens were mapped only by color, which caused loss of font-style metadata.
Now, styles like bold, italic, and strikethrough are correctly rendered across all supported themes.

### Summary of Changes

* Added `normalizeFontStyleString()` and `normalizeFontStyleBits()` to handle Shiki → Monaco font style mapping.
* Implemented dual mapping for:

  * `color → scope` (backward compatibility)
  * `color + style → scope` (for accurate style preservation)
* Updated `textmateThemeToMonacoTheme()` to forward `fontStyle` correctly.
* Simplified theme registration logic and removed redundant mappings.
* Verified behavior for Markdown tokens (`markup.bold`, `markup.italic`, `markup.strikethrough`).

---

### Linked Issue

Fixes #1022

---

### Testing & Verification

* **Env:** `monaco-editor@0.54.0`, Shiki themes `github-dark` / `github-light`.
* **API Check:**

  ```js
  editor._themeService._knownThemes.get('github-dark').tokenTheme._match('markup.bold')
  // → _fontStyle: 2 (bold)
  ```
* **Result:**
  **Bold**, *italic*, and ~~strikethrough~~ now render correctly; no regressions found.
* **Console:**

  ```
  Style applied: markup.bold bold
  Style applied: markup.italic italic
  Style applied: markup.strikethrough strikethrough
  ```

### Additional context
Verified theme switching (github-dark ↔ github-light) works correctly.

No regressions observed in syntax highlighting for other languages.

The change aligns Monaco’s highlighting fidelity with Shiki’s output.

### CODE REVIEW

File: packages/monaco/src/index.ts [hunk 1]
```diff
@@ -77,6 +77,7 @@ export function shikiToMonaco(
 
   const colorMap: string[] = []
   const colorToScopeMap = new Map<string, string>()
+  const colorAndStyleToScopeMap = new Map<string, string>()
```
Comment (antfu) [inline packages/monaco/src/index.ts]: Can we have these two maps together? When FontStyle is none, we just do `color`, for the key, and when it is present, we do `color|font-style`?

File: packages/monaco/src/index.ts [hunk 2]
```diff
@@ -154,3 +174,53 @@ export function shikiToMonaco(
...
+  const styles = new Set(
+    fontStyle
+      .split(/[\s,]+/)
+      .map(style => style.trim().toLowerCase())
+      .filter(Boolean),
+  )
+
+  styles.delete('')
+  styles.delete('normal')
+  styles.delete('none')
```
Comment (antfu) [inline packages/monaco/src/index.ts]: What are those?

File: packages/monaco/src/index.ts
Comment (antfu) [inline packages/monaco/src/index.ts]: Maybe we should normalize the fontStyle here? And I think we can do a simple alphabet sorting.

File: packages/monaco/src/index.ts (hunk 1 above)
Comment (prempyla) [reply packages/monaco/src/index.ts]: yes @antfu  ,Merged into a single colorStyleToScopeMap using color or color|font-style as key — simpler and avoids duplication.

**Comment by prempyla** [comment]
Hi @antfu , just checking in , I’ve made the requested changes and pushed the updates.
Please take a look when you get a chance. Thanks again for your time and feedback!

**Review by antfu — APPROVED** [review]
