### PR TITLE
fix(lang-ansi): Fallback for missing theme ANSI colors

### LINKED ISSUE #1059: ansi highlight not work
### Validations

- [x] Follow our [Code of Conduct](https://github.com/shikijs/shiki/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [Contributing Guide](https://github.com/shikijs/shiki/blob/main/CONTRIBUTING.md).
- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

### Describe the bug

language `ansi` not highlight with theme one-light

### Reproduction

https://codesandbox.io/p/sandbox/8k24zd

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

### PR DESCRIPTION
**Pull request by Chanakyasinde**
### Description

This PR fixes an issue where ANSI language highlighting (`lang: ansi`) would fail on themes that do not provide their own `terminal.ansi*` colors (as seen with `one-light`).

The original code would attempt to read `theme.colors` for the ANSI palette. If a theme didn't define these colors, `undefined` was passed to the `createColorPalette` function, causing an error.

This change introduces a `defaultAnsiColors` map, which provides a standard VSCode-compatible set of fallback colors. The `tokenizeAnsiWithTheme` function now checks for a theme color and uses a color from this default map if one isn't found, ensuring the ANSI tokenizer always receives valid color values.

### Linked Issues

Fixes #1059

### Additional context

The `defaultAnsiColors` map is based on the standard VSCode fallbacks. This ensures consistent behavior for themes that don't specify their own terminal colors, resolving the bug while maintaining correctness for themes that do.

### CODE REVIEW

File: packages/core/src/highlight/code-to-tokens-ansi.ts [hunk 1]
```diff
@@ -72,29 +96,20 @@ export function tokenizeAnsiWithTheme(
...
-      // convert from #rrggbb to #rrggbb80
       return `#${hexMatch[1]}${hexMatch[2]}80`
     }
     else {
-      // convert from #rgb to #rrggbb80
-      return `#${Array
-        .from(hexMatch[1])
-        .map(x => `${x}${x}`)
-        .join('')}80`
+      return `#${Array.from(hexMatch[1]).map(x => x + x).join('')}80`
```
Comment (antfu) [inline packages/core/src/highlight/code-to-tokens-ansi.ts]: Why do we touch this part of the code and removing the comments?

Comment (Chanakyasinde) [reply packages/core/src/highlight/code-to-tokens-ansi.ts]: Hi @antfu , you're right. Those changes were unintentional, likely from my local code formatter. They aren't related to the ANSI color fallback.

I'll revert them back to its original state and push a new commit. My apologies for the noise!
